# Generated by Django 5.1.7 on 2025-03-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='market',
        ),
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.ManyToManyField(related_name='products', to='market_app.market'),
        ),
    ]
