# Generated by Django 5.1.7 on 2025-03-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_remove_product_market_product_market'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='market',
            new_name='markets',
        ),
    ]
